#
# The following example uses:
#
# * uses manually created storages (pv & pvc)
# * nginx as reverse proxy
# * enables celery for exercise syncs
# * enables email
# * enables axes with reverse proxy configuration listening for X_FORWARDED_FOR header
# * modifies the gunicorn start parameters
# * enables a ingress assuming cert-manager is setup with a let's encrypt issuer and traefik
#
# Have a look at the packaged values.yaml for defaults and more settings:
#   * https://github.com/wger-project/helm-charts/blob/master/charts/wger/values.yaml
#
# App settings
app:
  timezone: "Etc/Zulu"
  mail:
    enabled: true
    server: mail.example.com
    user: wger@example.com
    from_email: "wger@example.com"
    secret:
      password: XXXXXXXXXXXXXXXXXXXXXXX

  axes:
    enabled: true
    failureLimit: 10
    # in minutes
    cooloffTime: 30
    # order of magnitude from last proxy for the real ip
    ipwareMetaPrecedenceOrder: "X_FORWARDED_FOR,REMOTE_ADDR"
  persistence:
    existingClaim:
      enabled: true
      media: wger-media
      static: wger-static
      celeryBeat: wger-celery-beat

ingress:
  enabled: true
  url: fit.example.com
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik

postgres:
  enabled: true
  settings:
    superuser:
      value: postgres
    superuserPassword:
      value: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  userDatabase:
    name:
      value: wger
    user:
      value: wger
    password:
      value: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  service:
    port: 5432
  storage:
    persistentVolumeClaimName: wger-db
    className: "csi-cephfs-sc"

redis:
  enabled: true
  auth:
    enabled: true
  # Additional environment variables (Redis server and Sentinel)
  # the secret is created by the wger chart as <release>-redis;
  # this example assumes the release is named "wger"
  env:
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: wger-redis
          key: redis-password
  # Arguments for the container entrypoint process (Redis server)
  args:
    - "--requirepass $(REDIS_PASSWORD)"
  storage:
    persistentVolumeClaimName: wger-redis
    className: "csi-cephfs-sc"
  service:
    serverPort: 6379
