apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    {{- include "wger.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.global.replicas }}
  strategy:
    # kills all old Pods first
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-app
      annotations:
        {{- include "wger.rollme.annotations" . | indent 8 }}
        {{- with .Values.app.global.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      # explicit set the default of 30s grace period
      # for the container to be SIGKILL'ed, pevents
      # powersync to start before old containers
      # are removed 
      terminationGracePeriodSeconds: 30
      {{- with .Values.app.global.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        # wger app container
        - name: wger
          image: {{ include "wger.image" . | quote }}
          imagePullPolicy: {{ .Values.app.global.image.pullPolicy }}
          env:
            {{- include "wger.env" . | indent 12 }}
            {{- include "database.settings" . | indent 10 }}
            {{- include "powersync.settings" . | indent 10 }}
            {{- include "wger.env.secrets" . | indent 10 }}
          ports:
            - name: app
              containerPort: 8000
              protocol: TCP
          # only accept network connection when ready
          # eg. when database migrations and collectstatic
          # have finished
          readinessProbe:
            httpGet:
              path: /
              port: app
            periodSeconds: 5
          {{- if .Values.app.resources }}
          resources:
            {{- with .Values.app.resources }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: wger-media
              mountPath: /home/wger/media
              readOnly: false
            - name: wger-static
              mountPath: /home/wger/static
              readOnly: false
            {{- if .Values.celery.enabled }}
            - name: wger-celery-beat
              mountPath: /home/wger/beat
              readOnly: false
            {{- end }}
      initContainers:
        - name: init-container
          image: {{ .Values.app.global.initImage }}
          imagePullPolicy: {{ .Values.app.global.image.pullPolicy }}
          command:
          {{- include "initContainer.pgonly.command" . | indent 10 }}
      volumes:
        - name: wger-media
          persistentVolumeClaim:
            claimName: {{ .Values.app.persistence.existingClaim.media | default (print .Release.Name "-media") | quote }}
        - name: wger-static
          persistentVolumeClaim:
            claimName: {{ .Values.app.persistence.existingClaim.static | default (print .Release.Name "-static") | quote }}
        {{- if .Values.celery.enabled }}
        - name: wger-celery-beat
          persistentVolumeClaim:
            claimName: {{ .Values.app.persistence.existingClaim.celeryBeat | default (print .Release.Name "-celery-beat") | quote }}
        {{- end }}
