{{- if .Values.celery.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-celery
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    {{- include "wger.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.celery.replicas }}
  strategy:
    # kills all old Pods first
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-celery
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-celery
      annotations:
        {{- include "wger.rollme.annotations" . | indent 8 }}
        {{- with .Values.celery.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.celery.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        # celery beat
        - name: celery-beat
          image: {{ include "wger.image" . | quote }}
          imagePullPolicy: {{ .Values.app.global.image.pullPolicy }}
          env:
            {{- include "wger.env" . | indent 12 }}
            {{- include "database.settings" . | indent 10 }}
            {{- include "powersync.settings" . | indent 10 }}
            {{- include "wger.env.secrets" . | indent 10 }}
          command: ["/start-beat"]
          volumeMounts:
            - name: wger-celery-beat
              mountPath: /home/wger/beat
              readOnly: false
          {{- if .Values.celery.resources }}
          resources:
            {{- with .Values.celery.resources }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
        # celery flower
        {{- if .Values.celery.flower.enabled }}
        - name: celery-flower
          image: {{ include "wger.image" . | quote }}
          imagePullPolicy: {{ .Values.app.global.image.pullPolicy }}
          env:
            {{- include "wger.env" . | indent 12 }}
            {{- include "database.settings" . | indent 10 }}
            {{- include "powersync.settings" . | indent 10 }}
            {{- include "wger.env.secrets" . | indent 10 }}
          command: ["/start-flower"]
          {{- if .Values.celery.flower.resources }}
          resources:
            {{- with .Values.celery.flower.resources }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          ports:
            - name: flower
              containerPort: 5555
              protocol: TCP
        {{- end }}
      initContainers:
        - name: init-container
          image: {{ .Values.app.global.initImage }}
          imagePullPolicy: {{ .Values.app.global.image.pullPolicy }}
          command:
          {{- include "initContainer.app.command" . | indent 10 }}
      volumes:
        - name: wger-celery-beat
          persistentVolumeClaim:
            claimName: {{ .Values.app.persistence.existingClaim.celeryBeat | default (print .Release.Name "-celery-beat") | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-celery-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    {{- include "wger.labels" . | nindent 4 }}
  {{- with .Values.celery.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.celery.replicasWorker }}
  strategy:
    # kills all old Pods first
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-celery-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-celery-worker
      annotations:
        {{- include "wger.rollme.annotations" . | indent 8 }}
        {{- with .Values.celery.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.celery.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        # celery worker
        - name: celery-worker
          image: {{ include "wger.image" . | quote }}
          imagePullPolicy: {{ .Values.app.global.image.pullPolicy }}
          env:
            {{- include "wger.env" . | indent 12 }}
            {{- include "database.settings" . | indent 10 }}
            {{- include "powersync.settings" . | indent 10 }}
            {{- include "wger.env.secrets" . | indent 10 }}
          command: ["/start-worker"]
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - celery -A wger inspect ping
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: wger-media
              mountPath: /home/wger/media
              readOnly: false
          {{- if .Values.celery.resources }}
          resources:
            {{- with .Values.celery.resources }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
      initContainers:
      - name: init-container
        image: {{ .Values.app.global.initImage }}
        imagePullPolicy: {{ .Values.app.global.image.pullPolicy }}
        command:
        {{- include "initContainer.app.command" . | indent 10 }}
      volumes:
        - name: wger-media
          persistentVolumeClaim:
            claimName: {{ .Values.app.persistence.existingClaim.media | default (print .Release.Name "-media") | quote }}
        - name: wger-celery-beat
          persistentVolumeClaim:
            claimName: {{ .Values.app.persistence.existingClaim.celeryBeat | default (print .Release.Name "-celery-beat") | quote }}
{{- end }}
