apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.global.replicas }}
  strategy:
    # kills all old Pods first
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-app
      annotations:
        # restart on upgrade
        rollme: {{ randAlphaNum 5 | quote }}
    {{- with .Values.app.global.annotations }}
      {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote}}
      {{- end }}
    {{- end }}
    spec:
      # explicit set the default of 30s grace period
      # for the container to be SIGKILL'ed, pevents
      # powersync to start before old containers
      # are removed 
      terminationGracePeriodSeconds: 30
      {{- with .Values.app.global.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        # wger app container
        - name: wger
          image: "{{ .Values.app.global.image.registry }}/{{ .Values.app.global.image.repository }}:{{ .Values.app.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.global.image.PullPolicy }}
          env:
            {{- include "wger.env" . | indent 12 }}
            {{- include "database.settings" . | indent 10 }}
            {{- include "powersync.settings" . | indent 10 }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.django.secret.name | default "django" | quote }}
                  key: "secret-key"
            {{- if .Values.app.mail.enabled }}
            - name: EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.mail.secret.name | default "mail" | quote }}
                  key: {{ .Values.app.mail.secret.key | default "mail-password" | quote }}
            {{- end }}
            # to enable redis authentication
            # additional settings in the values
            # must be made, passed to the redis
            # container
            {{- if .Values.redis.auth.enabled }}
            - name: DJANGO_CACHE_CLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "redis"
                  key: "redis-password"
            - name: CELERY_BROKER
              value: "redis://:$(DJANGO_CACHE_CLIENT_PASSWORD)@{{ .Release.Name }}-redis:{{ int .Values.redis.service.serverPort }}/2"
            - name: CELERY_BACKEND
              value: "redis://:$(DJANGO_CACHE_CLIENT_PASSWORD)@{{ .Release.Name }}-redis:{{ int .Values.redis.service.serverPort }}/2"
            {{- else }}
            - name: CELERY_BROKER
              value: "redis://{{ .Release.Name }}-redis:{{ int .Values.redis.service.serverPort }}/2"
            - name: CELERY_BACKEND
              value: "redis://{{ .Release.Name }}-redis:{{ int .Values.redis.service.serverPort }}/2"
            # {{/*- if .Values.redis.auth.enabled */}}
            {{- end }}
            {{- if .Values.celery.flower.enabled }}
            - name: CELERY_FLOWER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.celery.flower.secret.name | default "flower" | quote }}
                  key: "password"
            {{- end }}
          ports:
            - name: app
              containerPort: 8000
              protocol: TCP
          # only accept network connection when ready
          # eg. when database migrations and collectstatic
          # have finished
          readinessProbe:
            httpGet:
              path: /
              port: app
            periodSeconds: 5
          {{- if .Values.app.resources }}
          resources:
            {{- with .Values.app.resources }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: wger-media
              mountPath: /home/wger/media
              readOnly: false
            - name: wger-static
              mountPath: /home/wger/static
              readOnly: false
            {{- if .Values.celery.enabled }}
            - name: wger-celery-beat
              mountPath: /home/wger/beat
              readOnly: false
            {{- end }}
      initContainers:
        - name: init-container
          image: docker.io/busybox:latest
          imagePullPolicy: {{ .Values.app.global.image.PullPolicy }}
          command:
          {{- include "initContainer.pgonly.command" . | indent 10 }}
      volumes:
        - name: wger-media
          persistentVolumeClaim:
            claimName: {{ .Values.app.persistence.existingClaim.media | default "wger-media" | quote }}
        - name: wger-static
          persistentVolumeClaim:
            claimName: {{ .Values.app.persistence.existingClaim.static | default "wger-static" | quote }}
        {{- if .Values.celery.enabled }}
        - name: wger-celery-beat
          persistentVolumeClaim:
            claimName: {{ .Values.app.persistence.existingClaim.celeryBeat | default "wger-celery-beat" | quote }}
        {{- end }}
