{{- if .Values.celery.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-celery
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.celery.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-celery
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-celery
      annotations:
    {{- with .Values.celery.annotations }}
      {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote}}
      {{- end }}
    {{- end }}
    spec:
      {{- with .Values.celery.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        # celery beat
        - name: celery-beat
          image: "{{ .Values.app.global.image.registry }}/{{ .Values.app.global.image.repository }}:{{ .Values.app.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.global.image.PullPolicy }}
          env:
            {{- include "wger.env" . | indent 12 }}
            {{- include "database.settings" . | indent 10 }}
            {{- include "powersync.settings" . | indent 10 }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.django.secret.name | default "django" | quote }}
                  key: "secret-key"
            {{- if .Values.app.mail.enabled }}
            - name: EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.mail.secret.name | default "mail" | quote }}
                  key: {{ .Values.app.mail.secret.key | default "mail-password" | quote }}
            {{- end }}
            # to enable redis authentication
            # additional settings in the values
            # must be made, passed to the redis
            # container
            {{- if .Values.redis.auth.enabled }}
            - name: DJANGO_CACHE_CLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "redis"
                  key: "redis-password"
            - name: CELERY_BROKER
              value: "redis://:$(DJANGO_CACHE_CLIENT_PASSWORD)@{{ .Release.Name }}-redis:{{ int .Values.redis.service.serverPort }}/2"
            - name: CELERY_BACKEND
              value: "redis://:$(DJANGO_CACHE_CLIENT_PASSWORD)@{{ .Release.Name }}-redis:{{ int .Values.redis.service.serverPort }}/2"
            {{- else }}
            - name: CELERY_BROKER
              value: "redis://{{ .Release.Name }}-redis:{{ int .Values.redis.service.serverPort }}/2"
            - name: CELERY_BACKEND
              value: "redis://{{ .Release.Name }}-redis:{{ int .Values.redis.service.serverPort }}/2"
            # {{/*- if .Values.redis.auth.enabled */}}
            {{- end }}
            {{- if .Values.celery.flower.enabled }}
            - name: CELERY_FLOWER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.celery.flower.secret.name | default "flower" | quote }}
                  key: "password"
            {{- end }}
          command: ["/start-beat"]
          volumeMounts:
            - name: wger-celery-beat
              mountPath: /home/wger/beat
              readOnly: false
          {{- if .Values.celery.resources }}
          resources:
            {{- with .Values.celery.resources }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
        # celery flower
        {{- if .Values.celery.flower.enabled }}
        - name: celery-flower
          image: "{{ .Values.app.global.image.registry }}/{{ .Values.app.global.image.repository }}:{{ .Values.app.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.global.image.PullPolicy }}
          env:
            {{- include "wger.env" . | indent 12 }}
            {{- include "database.settings" . | indent 10 }}
            {{- include "powersync.settings" . | indent 10 }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.django.secret.name | default "django" | quote }}
                  key: "secret-key"
            {{- if .Values.app.mail.enabled }}
            - name: EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.mail.secret.name | default "mail" | quote }}
                  key: {{ .Values.app.mail.secret.key | default "mail-password" | quote }}
            {{- end }}
            # to enable redis authentication
            # additional settings in the values
            # must be made, passed to the redis
            # container
            {{- if .Values.redis.auth.enabled }}
            - name: DJANGO_CACHE_CLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "redis"
                  key: "redis-password"
            - name: CELERY_BROKER
              value: "redis://:$(DJANGO_CACHE_CLIENT_PASSWORD)@{{ .Release.Name }}-redis:{{ int .Values.redis.service.serverPort }}/2"
            - name: CELERY_BACKEND
              value: "redis://:$(DJANGO_CACHE_CLIENT_PASSWORD)@{{ .Release.Name }}-redis:{{ int .Values.redis.service.serverPort }}/2"
            {{- else }}
            - name: CELERY_BROKER
              value: "redis://{{ .Release.Name }}-redis:{{ int .Values.redis.service.serverPort }}/2"
            - name: CELERY_BACKEND
              value: "redis://{{ .Release.Name }}-redis:{{ int .Values.redis.service.serverPort }}/2"
            # {{/*- if .Values.redis.auth.enabled */}}
            {{- end }}
            - name: CELERY_FLOWER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.celery.flower.secret.name | default "flower" | quote }}
                  key: "password"
          command: ["/start-flower"]
          {{- if .Values.celery.flower.resources }}
          resources:
            {{- with .Values.celery.flower.resources }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          ports:
            - name: flower
              containerPort: 5555
              protocol: TCP
        # {{/*- if .Values.celery.flower.enabled */}}
        {{- end }}
      initContainers:
        - name: init-container
          image: docker.io/busybox:latest
          command:
          {{- include "initContainer.web.command" . | indent 10 }}
      volumes:
        - name: wger-celery-beat
          persistentVolumeClaim:
            claimName: {{ .Values.app.persistence.existingClaim.celeryBeat | default "wger-celery-beat" | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-celery-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  {{- with .Values.celery.annotations }}
  annotations:
    {{- range $key, $value := . }}
      {{ $key }}: {{ $value | quote}}
    {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.celery.replicasWorker }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-celery-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-celery-worker
      annotations:
    {{- with .Values.celery.annotations }}
      {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote}}
      {{- end }}
    {{- end }}
    spec:
      {{- with .Values.celery.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        # celery worker
        - name: celery-worker
          image: "{{ .Values.app.global.image.registry }}/{{ .Values.app.global.image.repository }}:{{ .Values.app.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.global.image.PullPolicy }}
          env:
            {{- include "wger.env" . | indent 12 }}
            {{- include "database.settings" . | indent 10 }}
            {{- include "powersync.settings" . | indent 10 }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.django.secret.name | default "django" | quote }}
                  key: "secret-key"
            {{- if .Values.app.mail.enabled }}
            - name: EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.mail.secret.name | default "mail" | quote }}
                  key: {{ .Values.app.mail.secret.key | default "mail-password" | quote }}
            {{- end }}
            # to enable redis authentication
            # additional settings in the values
            # must be made, passed to the redis
            # container
            {{- if .Values.redis.auth.enabled }}
            - name: DJANGO_CACHE_CLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "redis"
                  key: "redis-password"
            - name: CELERY_BROKER
              value: "redis://:$(DJANGO_CACHE_CLIENT_PASSWORD)@{{ .Release.Name }}-redis:{{ int .Values.redis.service.serverPort }}/2"
            - name: CELERY_BACKEND
              value: "redis://:$(DJANGO_CACHE_CLIENT_PASSWORD)@{{ .Release.Name }}-redis:{{ int .Values.redis.service.serverPort }}/2"
            {{- else }}
            - name: CELERY_BROKER
              value: "redis://{{ .Release.Name }}-redis:{{ int .Values.redis.service.serverPort }}/2"
            - name: CELERY_BACKEND
              value: "redis://{{ .Release.Name }}-redis:{{ int .Values.redis.service.serverPort }}/2"
            # {{/*- if .Values.redis.auth.enabled */}}
            {{- end }}
            {{- if .Values.celery.flower.enabled }}
            - name: CELERY_FLOWER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.celery.flower.secret.name | default "flower" | quote }}
                  key: "password"
            {{- end }}
          command: ["/start-worker"]
          volumeMounts:
            - name: wger-media
              mountPath: /home/wger/media
              readOnly: false
          {{- if .Values.celery.resources }}
          resources:
            {{- with .Values.celery.resources }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
      initContainers:
      - name: init-container
        image: docker.io/busybox:latest
        command:
        {{- include "initContainer.web.command" . | indent 10 }}
      volumes:
        - name: wger-media
          persistentVolumeClaim:
            claimName: {{ .Values.app.persistence.existingClaim.media | default "wger-media" | quote }}
        - name: wger-celery-beat
          persistentVolumeClaim:
            claimName: {{ .Values.app.persistence.existingClaim.celeryBeat | default "wger-celery-beat" | quote }}
# {{/*- if .Values.celery.enabled */}}
{{- end }}
