apiVersion: v1
kind: Secret
metadata:
  name: powersync
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,pre-rollback
    helm.sh/hook-weight: "-5"
stringData:
  user: {{ .Values.powersync.secretDatabase.user | quote }}
{{ if .Values.powersync.secretDatabase.pw }}
  pw: {{ .Values.powersync.secretDatabase.pw | quote }}
{{ else }}
  {{- if .Release.IsUpgrade }}
    {{- if (lookup "v1" "Secret" .Release.Namespace "powersync") }}
  pw: {{ index (lookup "v1" "Secret" .Release.Namespace "powersync").data "pw" | b64dec | quote }}
    {{ else }}
  pw: {{ randAlphaNum 32 | quote }}
    {{- end }}
  {{ else }}
  pw: {{ randAlphaNum 32 | quote }}
  {{- end }}
{{- end }}
