# updates or creates the secret
{{- define "manipulate" -}}
{{- if (lookup "v1" "Secret" .Release.Namespace .Values.app.jwt.secret.name) -}}
  {{- if .Values.app.jwt.secret.update -}}
doit
  {{- end -}}
{{- else -}}
doit
{{- end -}}
{{- end -}}

{{- $manipulate := (include "manipulate" .) }}
{{- if eq $manipulate "doit" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.jwt.secret.name | default "jwt" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,pre-rollback
    helm.sh/hook-weight: "-5"
stringData:
  private-key: {{ .Values.app.jwt.secret.privateKey | quote }}
  public-key: {{ .Values.app.jwt.secret.publicKey | quote }}
{{- end }}
