apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wger.secretName.django" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,pre-rollback
    helm.sh/hook-weight: "-5"
stringData:
  secret-key: {{ include "wger.secretValue" (dict "ctx" $ "name" (include "wger.secretName.django" .) "key" "secret-key" "value" .Values.app.django.secret.key "length" 50 "legacyName" "django") | quote }}
