{{- if .Values.app.oauth2Provider.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wger.secretName.oidc" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,pre-rollback
    helm.sh/hook-weight: "-5"
stringData:
  private-key: {{ include "wger.secretValue" (dict "ctx" $ "name" (include "wger.secretName.oidc" .) "key" "private-key" "value" .Values.app.oauth2Provider.secret.privateKey "rsa" true) | quote }}
{{- end }}
