apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-powersync
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,pre-rollback
    helm.sh/hook-weight: "-5"
stringData:
  user: {{ .Values.powersync.secretDatabase.user | quote }}
  pw: {{ include "wger.secretValue" (dict "ctx" $ "name" (print .Release.Name "-powersync") "key" "pw" "value" .Values.powersync.secretDatabase.pw "length" 32 "legacyName" "powersync") | quote }}
