# for keygen, currently only used for jwt key generation
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-keygen
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,pre-rollback
    helm.sh/hook-weight: "-6"
